import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [message, setMessage] = useState("Not Ok");
  const callAPI = async () => {
    try {
      const res = await fetch(`http://0.0.0.0:3001/template`);
      const data = await res.json();
      setMessage(data.message);
      console.log(data);
    } catch (err) {
      console.log(err);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={callAPI}>gRPC Call</button>
        <p>{message}</p>
      </main>
    </div>
  );
}
